name: Build linux

on:
  pull_request:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        arch: [x64]
        mode: [release]

    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v4

    - name: 'Checkout submodules'
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1

    # Install dependencies
    - name: 'Update apt repositories'
      run: sudo apt-get update

    # Install xmake
    - name: 'Setup xmake'
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: branch@master

    # Update xmake repository (in order to have the file that will be cached)
    - name: 'Update xmake repository'
      run: xmake repo --update

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9

    # Setup compilation mode and install project dependencies
    - name: 'Configure xmake and install dependencies'
      continue-on-error: true
      run: timeout 30m xmake config --arch=${{ matrix.arch }} --mode=${{ matrix.mode }} --yes -vD

    # Build the server
    - name: Build
      run: xmake -y -vD
